version: "3.9"

services:
  app:
    build: .
    container_name: weconnect-app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=989878
      - DB_NAME=WECONDB
      - JWT_SECRET=Metacore@989/
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mariadb:10.6
    container_name: weconnect-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=989878
      - MYSQL_DATABASE=WECONDB
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql

  redis:
    image: redis:7-alpine
    container_name: weconnect-redis
    restart: always
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: weconnect-prometheus
    restart: always
    depends_on:
      - app
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:11.1.0
    container_name: weconnect-grafana
    restart: always
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro

volumes:
  db_data:
  prometheus_data:
  grafana_data:
